name: moveonjoy-epg-grabber

on:
  schedule:
    - cron: "0 */12 * * *"  # Every 12 hours
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-epg:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install requests

    - name: Run EPG builder
      run: python generate_epg.py

    - name: Commit and push generated EPG
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add epgs/*.xml epgs/*.gz
        git commit -m "Update EPG files [auto]" || echo "No changes to commit"
        git push
